### ISSUE TITLE
Error while sending photos, always get 400 from Insta

### ISSUE THREAD

**Issue by fconsigny** [ErrorxCode/EasyInsta#6]
Error while sending photos, always get 400 from Insta

```

File p = new File("temp.png");
            if(p.exists() ) {
                log.info("PICTURE EXIST "  + p.getName()) ;
            }

            AsyncTask<Void> t =  actions.postPhoto(new File("temp.png"), "Another cat stuff ");
            
```
            
            Below the response in an ErrorCallBackMethod : 

```
2022-06-17 14:38:12.582  INFO 23356 --- [stagram.com/...] c.g.instagram4j.instagram4j.IGClient     : Response for https://i.instagram.com/rupload_igphoto/1655473091424_0_5158328113 : 400
2022-06-17 14:38:12.583  INFO 23356 --- [stagram.com/...] c.g.instagram4j.instagram4j.IGClient     : Response for https://i.instagram.com/rupload_igphoto/1655473091424_0_5158328113 with body (truncated) : {"debug_info":{"retriable":false,"type":"ProcessingFailedError","message":"Request processing failed
2022-06-17 14:38:12.585  INFO 23356 --- [onPool-worker-1] c.s.a.s.instacash.service.UserService    : java.util.concurrent.ExecutionException: com.github.instagram4j.instagram4j.exceptions.IGResponseException
java.util.concurrent.CompletionException: java.util.concurrent.ExecutionException: com.github.instagram4j.instagram4j.exceptions.IGResponseException
	at com.xcoder.tasks.AsyncTask.lambda$callAsync$3(AsyncTask.java:42)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.util.concurrent.ExecutionException: com.github.instagram4j.instagram4j.exceptions.IGResponseException
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
	at com.xcoder.easyinsta.Instagram$Feed.lambda$postPhoto$0(Instagram.java:681)
	at com.xcoder.tasks.AsyncTask.lambda$callAsync$3(AsyncTask.java:40)
	... 7 more
	
```
	
	
	Seems like the Insta Client is always returning 400.
	
	Can you please check ?

**Comment by ErrorxCode** [comment]
Looks like it's your photo problem. Make sure it is of Instagram acceptable dimensions

**Comment by ErrorxCode** [comment]
Instagram allows photos of size 800*800
